### ISSUE TITLE
must process scenes in chronological order

### ISSUE THREAD

**Issue by bnordgren** [firelab/viirs_ba#13]
The way the code is written, scenes must be provided to the ImageDates option in the configuration file in chronological order. At the moment, I have them sorted manually.

It's probably better just to have the viirs_config object sort them. Or the get_dates utility emit them in sorted order.

**Comment by calbury** [comment]
Yep, crap, this is a huge oversite. When I put things together my testing data set was in chronological order and then I forgot about it. That proabably explains the trouble I was having with large fires.. I’ll put together a bit to sort the list.

[Forest Service Shield]

Carl Albury
Remote Sensing Specialist

Forest Service Contractor
Remote Sensing Applications Center

p: 801-975-3351
calbury@fs.fed.usmailto:calbury@fs.fed.us

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.ushttp://www.fs.fed.us/
[USDA Logo]http://usda.gov/[Forest Service Twitter]https://twitter.com/forestservice[USDA Facebook]https://www.facebook.com/pages/US-Forest-Service/1431984283714112

Caring for the land and serving people

**Comment by bnordgren** [comment]
You thinking to add to my viirs_config class, or to the processing code? I
think there's probably just a .sort() method on the list or something like
that.

**Comment by bnordgren** [comment]
Fixed in fom branch via 3dc08fab16d12da3bbd61703976b0541b59f0fe0
