### ISSUE TITLE
fire_events is multipoint type, causes problems with Arc

### ISSUE THREAD

**Issue by bnordgren** [firelab/viirs_ba#15]
Arc doesn't like extracting raster values using Multipoint geometries.

Are these vals really just a single point?

**Comment by calbury** [comment]
These are single part. I was initially thinking I would merge the points that make up a fire into a multipoint, but went  the fire_collection route instead. We could convert that field/table to siglepoint.

Carl

**Comment by bnordgren** [comment]
Good enough. I just wanted to make sure that making it a Point wouldn't step on your toes.
