### ISSUE TITLE
Hard coded distance

### ISSUE THREAD

**Issue by bnordgren** [firelab/viirs_ba#2]
viirs_simple_confirm_burns has a parameter for the distance threshold, but doesn't use it.

See: 

https://github.com/firelab/viirs_ba/blob/master/SqlFunctions/viirs_simple_confirm_burns.sql#L21

**Comment by calbury** [comment]
This issue is fixed, I pushed an old copy of the function instead of the function from the current database. I updated the function so that the distance is read from the input parameter.
