### ISSUE TITLE
Clean up arcpy

### ISSUE THREAD

**Issue by bnordgren** [firelab/viirs_ba#4]
The arcpy import is commented out, but some code still refers to it? Are we keeping this as a viable variant, or is this just a holdover from the first cut? 

If we are keeping this, maybe a separate arcpy module which imports the non-arcpy-having module is the way to go?

**Comment by calbury** [comment]
I pulled all of the arcpy functions and shapefile/raster language from the VIIRS_threshold_reflCor_Bulk.py script and ini file. I saved all of that language in a file called misc_utils/arcpy_functions.py
