### ISSUE TITLE
Selecting, then testing for existance

### ISSUE THREAD

**Issue by bnordgren** [firelab/viirs_ba#7]
in the viirs_threshold_2_fireevents method (and perhaps elsewhere) I see : 

```
SELECT * from ... LIMIT 1 into dumrec ; 
IF EXISTS (SELECT * from ... LIMIT 1) THEN
    blah
END
```

We may be able to cut the number of select statements in half if we take the approach here: http://stackoverflow.com/questions/7163996/how-to-select-into-a-variable-in-pl-sql-when-the-result-might-be-null

```
BEGIN
    SELECT * from ... LIMIT 1 into dumrec ; 
EXCEPTION
     WHEN NO_DATA_FOUND THEN 
        NULL ; 
 END;
```

**Comment by calbury** [comment]
I will look into this. I’ve never been satisfied with how complicated these queries are.

[Forest Service Shield]

Carl Albury
Remote Sensing Specialist

Forest Service Contractor
Remote Sensing Applications Center

p: 801-975-3351
calbury@fs.fed.usmailto:calbury@fs.fed.us

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.ushttp://www.fs.fed.us/
[USDA Logo]http://usda.gov/ [Forest Service Twitter] https://twitter.com/forestservice  [USDA Facebook] https://www.facebook.com/pages/US-Forest-Service/1431984283714112

Caring for the land and serving people

**Comment by bnordgren** [comment]
I restructured the threshold_burned part. It replaces the loop with a temporary table and single insert/update statements. Further pursuit of this topic should go on #16.
